# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  config.vm.box = "boxcutter/ubuntu1604"
  config.vm.hostname = "xenial"

  config.vm.provision :shell, :path => "provision.sh"

  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 8081, host: 8081
  config.vm.network :forwarded_port, guest: 8200, host: 8200
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh'

  config.vm.network :private_network, ip: "172.17.8.100"

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "8"
  end
end
